name = "observasenado-worker"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
# Domingos às 03:00 UTC (semanal)
crons = ["0 3 * * SUN"]

[[kv_namespaces]]
binding = "SENADO_CACHE"
id = "dcf03cd1a682464a87a1efba158ee109"
preview_id = "1b338b0fbd3844168bcffbc57675b135"

[[d1_databases]]
binding = "SENADO_DB"
database_name = "senado-db"
database_id = "6e4aa3f6-ecda-4caf-95a7-b120817c5a6b"

[vars]
ENVIRONMENT = "production"
LEGIS_BASE_URL = "https://legis.senado.leg.br/dadosabertos"
ADM_BASE_URL = "https://adm.senado.gov.br/adm-dadosabertos"
CACHE_TTL = "21600"
